[versions]
androidGradlePlugin = "7.4.2"
kotlin = "1.9.0"

compileSdk = "33"
minSdk = "24"
targetSdk = "33"
ios-deploymentTarget = "14.1"
jvmToolchain = "11"

androidx-core = "1.9.0"
androidx-activity-compose = "1.6.1"
androidx-appcompat = "1.6.1"
compose-version = "1.4.3"
accompanist-version = "0.28.0"
hilt-version = "2.46.1"
constraint-version = "1.0.1"
koin-version = "3.4.3"
voyager-version = "1.0.0-rc05"
koinKspVersion = "1.2.2"

voyager = "1.0.0-rc05"
ksp = "1.8.21-1.0.11"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-version" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-version" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-version" }
compose-materialIcons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-version" }


compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-version" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-version" }
androidx-ui-text = { group = "androidx.compose.ui", name = "ui-text", version = "1.4.3" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.1.1" }
google-accompanist = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-version"}
androidx-constraint = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraint-version"}
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-version"}
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin-version"}
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager-version"}
voyager-bottomsheet-navigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager-version"}
voyager-tab-navigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager-version"}
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager-version"}
voyager-androidx = { module = "cafe.adriel.voyager:voyager-androidx", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-version" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinKspVersion" }
koin-ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
koin-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinKspVersion" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-version" }
google-dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version"}
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }


